/**
 * Town Profile Schema
 * 
 * Structured document containing operational information about a town.
 * Generated by crawling town website and extracting key details.
 */

export interface TownProfile {
  // Metadata
  town: string;
  county: string;
  state: string;
  lastUpdated: string; // ISO date
  sourceUrls: string[];
  
  // Basic town information
  townHall: {
    address: string;
    phone?: string;
    fax?: string;
    email?: string;
    website?: string;
    hours?: {
      weekdays?: string;
      weekends?: string;
      notes?: string;
    };
  };
  
  // Boards and committees
  boards: {
    [boardName: string]: {
      name: string;
      meetingSchedule?: string; // "2nd and 4th Monday at 6:00 PM"
      location?: string;
      nextMeeting?: string; // ISO date if known
      agendaUrl?: string;
      minutesUrl?: string;
      contact?: string;
      currentMembers?: string[];
      notes?: string;
    };
  };
  
  // Departments and staff
  departments: {
    [deptName: string]: {
      name: string;
      staffName?: string; // Current staff member name
      title?: string; // "Town Clerk", "Tax Collector"
      phone?: string;
      email?: string;
      hours?: string;
      location?: string;
      notes?: string;
    };
  };
  
  // Services
  services?: {
    trash?: {
      schedule?: string;
      provider?: string;
      contact?: string;
      notes?: string;
    };
    recycling?: {
      schedule?: string;
      provider?: string;
      notes?: string;
    };
    transferStation?: {
      location?: string;
      hours?: string;
      fees?: string;
      acceptedItems?: string[];
      notes?: string;
    };
    other?: {
      [serviceName: string]: {
        description?: string;
        schedule?: string;
        contact?: string;
        notes?: string;
      };
    };
  };
  
  // Recreation
  recreation?: {
    beaches?: {
      name: string;
      location?: string;
      fees?: string;
      hours?: string;
    }[];
    parks?: {
      name: string;
      location?: string;
      facilities?: string[];
    }[];
    programs?: {
      name: string;
      description?: string;
      registration?: string;
      contact?: string;
    }[];
    notes?: string;
  };
  
  // Permits and licenses
  permits?: {
    [permitType: string]: {
      name: string;
      description?: string;
      fee?: string;
      requirements?: string[];
      contact?: string;
      applicationUrl?: string;
      notes?: string;
    };
  };
  
  // Tax information
  taxes?: {
    taxRate?: string; // Current year
    dueDate?: string; // "July 1 and December 1"
    paymentMethods?: string[];
    contact?: string;
    onlinePaymentUrl?: string;
    notes?: string;
  };
  
  // Voting/elections
  voting?: {
    registrationInfo?: string;
    pollingLocations?: {
      district?: string;
      location: string;
      address?: string;
    }[];
    absenteeInfo?: string;
    contact?: string;
    notes?: string;
  };
  
  // Additional notes
  notes?: string;
}

/**
 * Extraction hints for LLM
 */
export const EXTRACTION_PROMPTS = {
  system: `You are a data extraction assistant specializing in municipal information. Extract structured information from town websites into JSON format. Be precise and only include information you can verify from the content. Use null for missing fields.`,
  
  user: (townName: string, content: string) => `
Extract information about ${townName} from the following website content.

CRITICAL RULES:
1. Only extract facts explicitly stated in the content
2. Do not infer or make up information
3. For dates/times, preserve exact wording (e.g., "2nd and 4th Monday at 6 PM")
4. For contact info, include exact phone numbers, emails, addresses
5. Use null for any field you cannot find
6. If uncertain, mark with "?" prefix (e.g., "?Possibly Tuesdays")

Website content:
---
${content}
---

Return a JSON object matching the TownProfile schema. Focus on:
- Town hall address, phone, hours
- Board meeting schedules (especially Select Board, Planning Board)
- Department contacts (Town Clerk, Tax Collector, etc.)
- Service schedules (trash, recycling, transfer station)
- Recreation facilities (beaches, parks)
- Tax information (rates, due dates, payment methods)
`,
};

/**
 * Convert TownProfile to markdown for human review and indexing
 */
export function profileToMarkdown(profile: TownProfile): string {
  let md = `# ${profile.town} Town Profile\n\n`;
  md += `**Last Updated:** ${profile.lastUpdated}\n`;
  md += `**County:** ${profile.county}, ${profile.state}\n\n`;
  
  if (profile.sourceUrls.length > 0) {
    md += `**Sources:** ${profile.sourceUrls.join(', ')}\n\n`;
  }
  
  md += `---\n\n`;
  
  // Town Hall
  md += `## Town Hall\n\n`;
  md += `**Address:** ${profile.townHall.address}\n`;
  if (profile.townHall.phone) md += `**Phone:** ${profile.townHall.phone}\n`;
  if (profile.townHall.email) md += `**Email:** ${profile.townHall.email}\n`;
  if (profile.townHall.website) md += `**Website:** ${profile.townHall.website}\n`;
  if (profile.townHall.hours) {
    md += `\n**Hours:**\n`;
    if (profile.townHall.hours.weekdays) md += `- Weekdays: ${profile.townHall.hours.weekdays}\n`;
    if (profile.townHall.hours.weekends) md += `- Weekends: ${profile.townHall.hours.weekends}\n`;
    if (profile.townHall.hours.notes) md += `- Notes: ${profile.townHall.hours.notes}\n`;
  }
  md += `\n`;
  
  // Boards
  if (Object.keys(profile.boards).length > 0) {
    md += `## Boards & Committees\n\n`;
    for (const [key, board] of Object.entries(profile.boards)) {
      md += `### ${board.name}\n\n`;
      if (board.meetingSchedule) md += `**Meeting Schedule:** ${board.meetingSchedule}\n`;
      if (board.location) md += `**Location:** ${board.location}\n`;
      if (board.contact) md += `**Contact:** ${board.contact}\n`;
      if (board.agendaUrl) md += `**Agendas:** ${board.agendaUrl}\n`;
      if (board.currentMembers && board.currentMembers.length > 0) {
        md += `**Members:** ${board.currentMembers.join(', ')}\n`;
      }
      if (board.notes) md += `\n${board.notes}\n`;
      md += `\n`;
    }
  }
  
  // Departments
  if (Object.keys(profile.departments).length > 0) {
    md += `## Departments & Staff\n\n`;
    for (const [key, dept] of Object.entries(profile.departments)) {
      md += `### ${dept.name}\n\n`;
      if (dept.staffName) md += `**Staff:** ${dept.staffName}`;
      if (dept.title) md += ` (${dept.title})`;
      if (dept.staffName) md += `\n`;
      if (dept.phone) md += `**Phone:** ${dept.phone}\n`;
      if (dept.email) md += `**Email:** ${dept.email}\n`;
      if (dept.hours) md += `**Hours:** ${dept.hours}\n`;
      if (dept.notes) md += `\n${dept.notes}\n`;
      md += `\n`;
    }
  }
  
  // Services
  if (profile.services) {
    md += `## Services\n\n`;
    
    if (profile.services.trash) {
      md += `### Trash Collection\n\n`;
      if (profile.services.trash.schedule) md += `**Schedule:** ${profile.services.trash.schedule}\n`;
      if (profile.services.trash.provider) md += `**Provider:** ${profile.services.trash.provider}\n`;
      if (profile.services.trash.contact) md += `**Contact:** ${profile.services.trash.contact}\n`;
      if (profile.services.trash.notes) md += `\n${profile.services.trash.notes}\n`;
      md += `\n`;
    }
    
    if (profile.services.transferStation) {
      md += `### Transfer Station\n\n`;
      if (profile.services.transferStation.location) md += `**Location:** ${profile.services.transferStation.location}\n`;
      if (profile.services.transferStation.hours) md += `**Hours:** ${profile.services.transferStation.hours}\n`;
      if (profile.services.transferStation.fees) md += `**Fees:** ${profile.services.transferStation.fees}\n`;
      if (profile.services.transferStation.notes) md += `\n${profile.services.transferStation.notes}\n`;
      md += `\n`;
    }
  }
  
  // Recreation
  if (profile.recreation) {
    md += `## Recreation\n\n`;
    
    if (profile.recreation.beaches && profile.recreation.beaches.length > 0) {
      md += `### Beaches\n\n`;
      for (const beach of profile.recreation.beaches) {
        md += `**${beach.name}**\n`;
        if (beach.location) md += `- Location: ${beach.location}\n`;
        if (beach.fees) md += `- Fees: ${beach.fees}\n`;
        if (beach.hours) md += `- Hours: ${beach.hours}\n`;
        md += `\n`;
      }
    }
    
    if (profile.recreation.parks && profile.recreation.parks.length > 0) {
      md += `### Parks\n\n`;
      for (const park of profile.recreation.parks) {
        md += `**${park.name}**\n`;
        if (park.location) md += `- Location: ${park.location}\n`;
        if (park.facilities && park.facilities.length > 0) {
          md += `- Facilities: ${park.facilities.join(', ')}\n`;
        }
        md += `\n`;
      }
    }
  }
  
  // Taxes
  if (profile.taxes) {
    md += `## Taxes\n\n`;
    if (profile.taxes.taxRate) md += `**Tax Rate:** ${profile.taxes.taxRate}\n`;
    if (profile.taxes.dueDate) md += `**Due Dates:** ${profile.taxes.dueDate}\n`;
    if (profile.taxes.paymentMethods && profile.taxes.paymentMethods.length > 0) {
      md += `**Payment Methods:** ${profile.taxes.paymentMethods.join(', ')}\n`;
    }
    if (profile.taxes.contact) md += `**Contact:** ${profile.taxes.contact}\n`;
    if (profile.taxes.onlinePaymentUrl) md += `**Online Payment:** ${profile.taxes.onlinePaymentUrl}\n`;
    md += `\n`;
  }
  
  // Permits
  if (profile.permits && Object.keys(profile.permits).length > 0) {
    md += `## Permits & Licenses\n\n`;
    for (const [key, permit] of Object.entries(profile.permits)) {
      md += `### ${permit.name}\n\n`;
      if (permit.description) md += `${permit.description}\n\n`;
      if (permit.fee) md += `**Fee:** ${permit.fee}\n`;
      if (permit.contact) md += `**Contact:** ${permit.contact}\n`;
      if (permit.applicationUrl) md += `**Application:** ${permit.applicationUrl}\n`;
      md += `\n`;
    }
  }
  
  if (profile.notes) {
    md += `## Additional Notes\n\n${profile.notes}\n\n`;
  }
  
  md += `---\n\n`;
  md += `*This profile was automatically generated by crawling the town website. Please verify all information before use.*\n`;
  
  return md;
}
